### ISSUE TITLE
:memo: (Docs) Writing the System Requirements Specification

### ISSUE THREAD

**Issue by evilcomrade** [COS301-SE-2022/MathU-Similarity-Index#2]
As per the demo 1 spec at the bare minimum it should have:
• Introduction
• User characteristics
• Functional requirements
• Service Contracts
• Class diagram
• Quality requirements
• Trace-ability matrix

There is an initial word document in the google drive, but the team will most likely meet together to fill it out collaboratively.

**Comment by TAWANDA-CODER** [comment]
80% done should be fully complete by 12th May
